"""Initial migration

Revision ID: 40e56b0f9003
Revises: 
Create Date: 2025-09-18 22:02:34.515223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e56b0f9003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('backup_name', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('integrity_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('ram_usage', sa.Float(), nullable=True),
    sa.Column('disk_usage', sa.Float(), nullable=True),
    sa.Column('network_usage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.drop_index('ix_backuprecord_job_name', table_name='backuprecord')
    op.drop_table('backuprecord')
    op.drop_table('systemmetric')
    op.drop_index('ix_botexecution_bot_name', table_name='botexecution')
    op.drop_table('botexecution')
    op.drop_index('ix_configurationentry_category', table_name='configurationentry')
    op.drop_index('ix_configurationentry_key', table_name='configurationentry')
    op.drop_table('configurationentry')
    op.drop_table('powerevent')
    op.drop_table('notificationrecord')
    op.drop_index('ix_useraction_session_id', table_name='useraction')
    op.drop_table('useraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(), nullable=False),
    sa.Column('component', sa.VARCHAR(), nullable=False),
    sa.Column('details', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_useraction_session_id', 'useraction', ['session_id'], unique=False)
    op.create_table('notificationrecord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.VARCHAR(), nullable=False),
    sa.Column('channels', sa.VARCHAR(), nullable=False),
    sa.Column('sent_at', sa.DATETIME(), nullable=False),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('powerevent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('battery_percent', sa.FLOAT(), nullable=True),
    sa.Column('triggered_by', sa.VARCHAR(), nullable=False),
    sa.Column('details', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurationentry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('value_type', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_configurationentry_key', 'configurationentry', ['key'], unique=False)
    op.create_index('ix_configurationentry_category', 'configurationentry', ['category'], unique=False)
    op.create_table('botexecution',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bot_name', sa.VARCHAR(), nullable=False),
    sa.Column('bot_type', sa.VARCHAR(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('result', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_botexecution_bot_name', 'botexecution', ['bot_name'], unique=False)
    op.create_table('systemmetric',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('cpu_percent', sa.FLOAT(), nullable=False),
    sa.Column('memory_percent', sa.FLOAT(), nullable=False),
    sa.Column('disk_percent', sa.FLOAT(), nullable=False),
    sa.Column('network_sent', sa.FLOAT(), nullable=False),
    sa.Column('network_recv', sa.FLOAT(), nullable=False),
    sa.Column('process_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backuprecord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_name', sa.VARCHAR(), nullable=False),
    sa.Column('backup_type', sa.VARCHAR(), nullable=False),
    sa.Column('source_paths', sa.VARCHAR(), nullable=False),
    sa.Column('destination_path', sa.VARCHAR(), nullable=False),
    sa.Column('total_size', sa.INTEGER(), nullable=True),
    sa.Column('files_count', sa.INTEGER(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backuprecord_job_name', 'backuprecord', ['job_name'], unique=False)
    op.drop_table('settings')
    op.drop_table('notifications')
    op.drop_table('metrics')
    op.drop_table('bot_runs')
    op.drop_table('backups')
    # ### end Alembic commands ###
