from typing import Protocol, Any, Dict, Optional

class ILogger(Protocol):
    def info(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: str, *args: Any, **kwargs: Any) -> None: ...

class IConfigManager(Protocol):
    def get(self, key: str, default: Optional[Any] = None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def load(self) -> None: ...

class IDataRepository(Protocol):
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def query(self, *args: Any, **kwargs: Any) -> Any: ...

class ITaskScheduler(Protocol):
    def schedule(self, name: str, cron: str, func: Any) -> None: ...
    def run_pending(self) -> None: ...

class INotificationManager(Protocol):
    def send(self, channel: str, message: str, metadata: Optional[Dict[str, Any]] = None) -> None: ...


__all__ = [
    'ILogger',
    'IConfigManager',
    'IDataRepository',
    'ITaskScheduler',
    'INotificationManager'
]
